# Generated by Django 5.0.6 on 2026-09-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('word_document_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'started_at'], name='local_sessi_submiss_ebf27f_idx')],
            },
        ),
    ]
