# Generated by Django 5.0.6 on 2026-09-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_sessions', '0001_initial'),
        ('snapshots', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_event_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('event_type', models.CharField(choices=[('session_started', 'Session started'), ('session_ended', 'Session ended'), ('document_opened', 'Document opened'), ('document_closed', 'Document closed'), ('insertion', 'Insertion'), ('deletion', 'Deletion'), ('replacement', 'Replacement'), ('large_insertion', 'Large insertion'), ('large_deletion', 'Large deletion'), ('formatting_change', 'Formatting change'), ('paragraph_added', 'Paragraph added'), ('paragraph_deleted', 'Paragraph deleted'), ('undo', 'Undo'), ('redo', 'Redo'), ('idle_started', 'Inactivity period started'), ('idle_ended', 'Inactivity period ended'), ('significant_change', 'Significant change'), ('submission_started', 'Submission started'), ('submission_completed', 'Submission completed'), ('synchronization', 'Synchronization'), ('connection_lost', 'Connection lost'), ('connection_restored', 'Connection restored')], max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('document_position', models.IntegerField(blank=True, null=True)),
                ('paragraph_index', models.IntegerField(blank=True, null=True)),
                ('character_offset', models.IntegerField(blank=True, null=True)),
                ('characters_affected', models.IntegerField(default=0)),
                ('words_affected', models.IntegerField(default=0)),
                ('inserted_text', models.TextField(blank=True, null=True)),
                ('deleted_text', models.TextField(blank=True, null=True)),
                ('previous_word_count', models.IntegerField(default=0)),
                ('new_word_count', models.IntegerField(default=0)),
                ('detection_method', models.CharField(blank=True, max_length=100)),
                ('classification_confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='local_sessions.writingsession')),
                ('snapshot_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_after', to='snapshots.documentsnapshot')),
                ('snapshot_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_before', to='snapshots.documentsnapshot')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='submissions.submission')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['submission', 'timestamp'], name='events_fore_submiss_8403f7_idx'), models.Index(fields=['submission', 'event_type'], name='events_fore_submiss_9d4db1_idx')],
            },
        ),
    ]
