# Generated by Django 5.0.6 on 2026-09-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='isolation-forest-v1', max_length=50)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('writing_pattern_score', models.FloatField(default=0.0)),
                ('insertion_pattern_score', models.FloatField(default=0.0)),
                ('editing_pattern_score', models.FloatField(default=0.0)),
                ('authorship_consistency_indicator', models.FloatField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True)),
                ('feature_data', models.JSONField(blank=True, null=True)),
                ('signals', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_analyses', to='submissions.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
