# Generated by Django 5.0.6 on 2026-09-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_sessions', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_snapshot_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('sequence_number', models.PositiveIntegerField()),
                ('document_version', models.PositiveIntegerField(default=1)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('cursor_position', models.IntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('content_changed', models.BooleanField(default=False)),
                ('change_type', models.CharField(blank=True, max_length=50)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('full_content', models.TextField(blank=True, null=True)),
                ('is_full_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_snapshots', to='snapshots.documentsnapshot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='local_sessions.writingsession')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='submissions.submission')),
            ],
            options={
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['submission', 'timestamp'], name='snapshots_d_submiss_b7d8e2_idx'), models.Index(fields=['session', 'timestamp'], name='snapshots_d_session_7d6936_idx'), models.Index(fields=['submission', 'sequence_number'], name='snapshots_d_submiss_874665_idx')],
            },
        ),
    ]
